# Generated by Django 3.0.2 on 2020-01-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200114_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_od_birth',
            new_name='date_of_birth',
        ),
    ]
